---
title: "2020-07-29 - Varried Selection Pressure - Experiment Analysis"
output:
  html_document:
    keep_md: no
    toc: true
    toc_float: true
    toc_depth: 4
    collapsed: false
    theme: default
    code_folding: hide
  pdf_document:
    toc: true
    toc_depth: 4
---

## Analysis Dependencies

```{r, message=FALSE}
library(ggplot2)   # (Wickham, 2016)
library(tidyr)     # (Wickham and Henry, 2020)
library(dplyr)     # (Wickham et al., 2020)
library(reshape2)  # (Wickham, 2007)
library(cowplot)   # (Wilke, 2019)
library(patchwork) # (Pedersen, 2020)
```

We conducted these analyses using the following computing environment:

```{r}
print(version)
```

```{r}
theme_set(theme_cowplot())

data_path <- "./data/agg_data.csv"
agg_data <- read.csv(data_path, na.strings="NONE")

agg_data$BIT_FLIP_PROB <- as.factor(agg_data$BIT_FLIP_PROB)
agg_data$DRIFT <- agg_data$TOURNAMENT_SIZE==1
agg_data$NUM_GENES <- as.factor(agg_data$NUM_GENES)
agg_data$NUM_BITS <- as.factor(agg_data$NUM_BITS)
agg_data$TOURNAMENT_SIZE <- as.factor(agg_data$TOURNAMENT_SIZE)

# Label
chg_rate_label <- function(mag, interval, drift) {
  if (drift) { return("drift") }
  else if (interval == 0) { return("0") }
  else { return(paste(mag, interval, sep="/")) }
}

agg_data$chg_rate_label <- factor(mapply(chg_rate_label, 
                                            agg_data$CHANGE_MAGNITUDE,
                                            agg_data$CHANGE_FREQUENCY,
                                            agg_data$DRIFT),
                                     levels=c("drift", "0", "1/256", "1/128",
                                              "1/64", "1/32", "1/16", "1/8",
                                              "1/4", "1/2", "1/1", "2/1", 
                                              "4/1", "8/1", "16/1", "32/1",
                                              "64/1", "128/1", "256/1", 
                                              "512/1", "1024/1", "2048/1",
                                              "4096/1"))

data_nk_phase_0 <- filter(agg_data, GRADIENT_MODEL==0 & evo_phase == 0 & update==50000)
data_gradient_phase_0 <- filter(agg_data, GRADIENT_MODEL==1 & evo_phase == 0 & update==50000)

```

## Evolution experiment

We evolved populations for 50,000 generations.

### Coding Sites

#### Gradient model

```{r}
ggplot(data_gradient_phase_0, 
       aes(x=chg_rate_label, y=coding_sites, color=chg_rate_label)) +
  geom_boxplot() +
  geom_jitter(alpha=0.25) +
  ylim(0, 129) +
  facet_grid(BIT_FLIP_PROB~TOURNAMENT_SIZE) +
  ggtitle("Gradient Fitness Model") +
  theme(legend.position = "none") +
  theme(panel.background = element_rect(fill = "grey90"))
```

#### NK model

```{r}
ggplot(data_nk_phase_0, 
       aes(x=chg_rate_label, y=coding_sites, color=chg_rate_label)) +
  geom_boxplot() +
  geom_jitter(alpha=0.25) +
  ylim(0, 129) +
  facet_grid(BIT_FLIP_PROB~TOURNAMENT_SIZE) +
  ggtitle("NK Fitness Model") +
  theme(legend.position = "none") +
  theme(panel.background = element_rect(fill = "grey90"))
```

### Genome Length

#### Gradient model

```{r}
ggplot(data_gradient_phase_0, 
       aes(x=chg_rate_label, y=genome_length, color=chg_rate_label)) +
  geom_boxplot() +
  geom_jitter(alpha=0.25) +
  facet_grid(BIT_FLIP_PROB~TOURNAMENT_SIZE) +
  ggtitle("Gradient Fitness Model") +
  theme(legend.position = "none") +
  theme(panel.background = element_rect(fill = "grey90"))
```

#### NK model

```{r}
ggplot(data_nk_phase_0, 
       aes(x=chg_rate_label, y=genome_length, color=chg_rate_label)) +
  geom_boxplot() +
  geom_jitter(alpha=0.25) +
  facet_grid(BIT_FLIP_PROB~TOURNAMENT_SIZE) +
  ggtitle("NK Fitness Model") +
  theme(legend.position = "none") +
  theme(panel.background = element_rect(fill = "grey90"))
```

### Fitness

#### Gradient model

```{r}
ggplot(data_gradient_phase_0, 
       aes(x=chg_rate_label, y=fitness, color=chg_rate_label)) +
  geom_boxplot() +
  geom_jitter(alpha=0.25) +
  facet_grid(BIT_FLIP_PROB~TOURNAMENT_SIZE) +
  ggtitle("Gradient Fitness Model") +
  theme(legend.position = "none") +
  theme(panel.background = element_rect(fill = "grey90"))
```

#### NK model

```{r}
ggplot(data_nk_phase_0, 
       aes(x=chg_rate_label, y=fitness, color=chg_rate_label)) +
  geom_boxplot() +
  geom_jitter(alpha=0.25) +
  facet_grid(BIT_FLIP_PROB~TOURNAMENT_SIZE) +
  ggtitle("NK Fitness Model") +
  theme(legend.position = "none") +
  theme(panel.background = element_rect(fill = "grey90"))
```

### Fitness ~ Coding Sites

```{r}
ggplot(data_gradient_phase_0, 
       aes(x=coding_sites, y=fitness, color=chg_rate_label)) +
  geom_point() +
  facet_grid(BIT_FLIP_PROB~TOURNAMENT_SIZE, scales="free") +
  ggtitle("Gradient Fitness Model") +
  theme(legend.position = "top") +
  theme(panel.background = element_rect(fill = "grey90"))
```

```{r}
ggplot(data_nk_phase_0, 
       aes(x=coding_sites, y=fitness, color=chg_rate_label)) +
  geom_point() +
  facet_grid(BIT_FLIP_PROB~TOURNAMENT_SIZE, scales="free") +
  ggtitle("NK Fitness Model") +
  theme(legend.position = "top") +
  theme(panel.background = element_rect(fill = "grey90"))
```