---
title: "2020-09-24"
output:
  html_document:
    keep_md: no
    toc: true
    toc_float: true
    toc_depth: 4
    collapsed: false
    theme: default
    code_folding: hide
  pdf_document:
    toc: true
    toc_depth: 4
---

## Analysis Dependencies

```{r, message=FALSE}
library(ggplot2)   # (Wickham, 2016)
library(tidyr)     # (Wickham and Henry, 2020)
library(dplyr)     # (Wickham et al., 2020)
library(reshape2)  # (Wickham, 2007)
library(cowplot)   # (Wilke, 2019)
library(patchwork) # (Pedersen, 2020)
```


We conducted these analyses using the following computing environment:

```{r}
print(version)
```

```{r}
theme_set(theme_cowplot())

data_path <- "mutant_samples.csv"
data <- read.csv(data_path, na.strings="NONE")

data$overlap <- factor(
  data$overlap,
  levels=c(0, 8, 16)
)

data$mutation_rate <- factor(
  data$mutation_rate,
  levels=c(0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 1.0)
)
```

```{r}

ggplot(data=data, aes(x=mutation_rate, color=overlap, y=parent_fitness)) +
  geom_boxplot() +
  ggsave("parent_fitness.pdf", width=10, height=10)

ggplot(data=data, aes(x=mutation_rate, color=overlap, y=offspring_fitness)) +
  geom_boxplot() +
  ggsave("mutant_fitness.pdf", width=10, height=10)

ggplot(data=data, aes(x=mutation_rate, color=overlap, y=fitness_difference)) +
  geom_boxplot() +
  ggsave("mutant_fitness_diff.pdf", width=10, height=10)

ggplot(data=data, aes(x=mutation_rate, color=overlap, y=num_mutations)) +
  geom_boxplot() +
  ggsave("num_mutations.pdf", width=10, height=10)
```